#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parador
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Parador_SanTiago")]
	public partial class DatasqlDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Inserttbl_Estado(tbl_Estado instance);
    partial void Updatetbl_Estado(tbl_Estado instance);
    partial void Deletetbl_Estado(tbl_Estado instance);
    partial void InserttblDetallePedido(tblDetallePedido instance);
    partial void UpdatetblDetallePedido(tblDetallePedido instance);
    partial void DeletetblDetallePedido(tblDetallePedido instance);
    partial void InserttblFacturaDetalle(tblFacturaDetalle instance);
    partial void UpdatetblFacturaDetalle(tblFacturaDetalle instance);
    partial void DeletetblFacturaDetalle(tblFacturaDetalle instance);
    partial void InserttblMenu(tblMenu instance);
    partial void UpdatetblMenu(tblMenu instance);
    partial void DeletetblMenu(tblMenu instance);
    partial void InserttblMesas(tblMesas instance);
    partial void UpdatetblMesas(tblMesas instance);
    partial void DeletetblMesas(tblMesas instance);
    partial void InserttblPedidos(tblPedidos instance);
    partial void UpdatetblPedidos(tblPedidos instance);
    partial void DeletetblPedidos(tblPedidos instance);
    partial void InserttblMeseros(tblMeseros instance);
    partial void UpdatetblMeseros(tblMeseros instance);
    partial void DeletetblMeseros(tblMeseros instance);
    partial void InserttblUsuarios(tblUsuarios instance);
    partial void UpdatetblUsuarios(tblUsuarios instance);
    partial void DeletetblUsuarios(tblUsuarios instance);
    partial void InserttblFacturas(tblFacturas instance);
    partial void UpdatetblFacturas(tblFacturas instance);
    partial void DeletetblFacturas(tblFacturas instance);
    partial void Inserttbl_FechaClientes(tbl_FechaClientes instance);
    partial void Updatetbl_FechaClientes(tbl_FechaClientes instance);
    partial void Deletetbl_FechaClientes(tbl_FechaClientes instance);
    partial void InserttblCliente(tblCliente instance);
    partial void UpdatetblCliente(tblCliente instance);
    partial void DeletetblCliente(tblCliente instance);
    #endregion
		
		public DatasqlDataContext() : 
				base(global::Parador.Properties.Settings.Default.Parador_SanTiagoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DatasqlDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatasqlDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatasqlDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatasqlDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_Estado> tbl_Estado
		{
			get
			{
				return this.GetTable<tbl_Estado>();
			}
		}
		
		public System.Data.Linq.Table<tblDetallePedido> tblDetallePedido
		{
			get
			{
				return this.GetTable<tblDetallePedido>();
			}
		}
		
		public System.Data.Linq.Table<tblFacturaDetalle> tblFacturaDetalle
		{
			get
			{
				return this.GetTable<tblFacturaDetalle>();
			}
		}
		
		public System.Data.Linq.Table<tblMenu> tblMenu
		{
			get
			{
				return this.GetTable<tblMenu>();
			}
		}
		
		public System.Data.Linq.Table<tblMesas> tblMesas
		{
			get
			{
				return this.GetTable<tblMesas>();
			}
		}
		
		public System.Data.Linq.Table<tblPedidos> tblPedidos
		{
			get
			{
				return this.GetTable<tblPedidos>();
			}
		}
		
		public System.Data.Linq.Table<tblMeseros> tblMeseros
		{
			get
			{
				return this.GetTable<tblMeseros>();
			}
		}
		
		public System.Data.Linq.Table<tblUsuarios> tblUsuarios
		{
			get
			{
				return this.GetTable<tblUsuarios>();
			}
		}
		
		public System.Data.Linq.Table<tblFacturas> tblFacturas
		{
			get
			{
				return this.GetTable<tblFacturas>();
			}
		}
		
		public System.Data.Linq.Table<Vista_Menu2> Vista_Menu2
		{
			get
			{
				return this.GetTable<Vista_Menu2>();
			}
		}
		
		public System.Data.Linq.Table<Vista_Historial> Vista_Historial
		{
			get
			{
				return this.GetTable<Vista_Historial>();
			}
		}
		
		public System.Data.Linq.Table<Color_states> Color_states
		{
			get
			{
				return this.GetTable<Color_states>();
			}
		}
		
		public System.Data.Linq.Table<tbl_FechaClientes> tbl_FechaClientes
		{
			get
			{
				return this.GetTable<tbl_FechaClientes>();
			}
		}
		
		public System.Data.Linq.Table<tblCliente> tblCliente
		{
			get
			{
				return this.GetTable<tblCliente>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Change")]
		public int Change([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Search")]
		public ISingleResult<SearchResult> Search([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string xxx)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), xxx);
			return ((ISingleResult<SearchResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.show_menu")]
		public ISingleResult<show_menuResult> show_menu([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idmesa)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idmesa);
			return ((ISingleResult<show_menuResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Estado")]
	public partial class tbl_Estado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Estado;
		
		private EntitySet<tblFacturas> _tblFacturas;
		
		private EntitySet<tbl_FechaClientes> _tbl_FechaClientes;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnEstadoChanging(string value);
    partial void OnEstadoChanged();
    #endregion
		
		public tbl_Estado()
		{
			this._tblFacturas = new EntitySet<tblFacturas>(new Action<tblFacturas>(this.attach_tblFacturas), new Action<tblFacturas>(this.detach_tblFacturas));
			this._tbl_FechaClientes = new EntitySet<tbl_FechaClientes>(new Action<tbl_FechaClientes>(this.attach_tbl_FechaClientes), new Action<tbl_FechaClientes>(this.detach_tbl_FechaClientes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Estado_tblFacturas", Storage="_tblFacturas", ThisKey="Id", OtherKey="IdEstado")]
		public EntitySet<tblFacturas> tblFacturas
		{
			get
			{
				return this._tblFacturas;
			}
			set
			{
				this._tblFacturas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Estado_tbl_FechaClientes", Storage="_tbl_FechaClientes", ThisKey="Id", OtherKey="IdEstado")]
		public EntitySet<tbl_FechaClientes> tbl_FechaClientes
		{
			get
			{
				return this._tbl_FechaClientes;
			}
			set
			{
				this._tbl_FechaClientes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblFacturas(tblFacturas entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Estado = this;
		}
		
		private void detach_tblFacturas(tblFacturas entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Estado = null;
		}
		
		private void attach_tbl_FechaClientes(tbl_FechaClientes entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Estado = this;
		}
		
		private void detach_tbl_FechaClientes(tbl_FechaClientes entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Estado = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblDetallePedido")]
	public partial class tblDetallePedido : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _IdPedido;
		
		private int _IdMenu;
		
		private int _Cantidad;
		
		private EntityRef<tblMenu> _tblMenu;
		
		private EntityRef<tblPedidos> _tblPedidos;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdPedidoChanging(int value);
    partial void OnIdPedidoChanged();
    partial void OnIdMenuChanging(int value);
    partial void OnIdMenuChanged();
    partial void OnCantidadChanging(int value);
    partial void OnCantidadChanged();
    #endregion
		
		public tblDetallePedido()
		{
			this._tblMenu = default(EntityRef<tblMenu>);
			this._tblPedidos = default(EntityRef<tblPedidos>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPedido", DbType="Int NOT NULL")]
		public int IdPedido
		{
			get
			{
				return this._IdPedido;
			}
			set
			{
				if ((this._IdPedido != value))
				{
					if (this._tblPedidos.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdPedidoChanging(value);
					this.SendPropertyChanging();
					this._IdPedido = value;
					this.SendPropertyChanged("IdPedido");
					this.OnIdPedidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMenu", DbType="Int NOT NULL")]
		public int IdMenu
		{
			get
			{
				return this._IdMenu;
			}
			set
			{
				if ((this._IdMenu != value))
				{
					if (this._tblMenu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdMenuChanging(value);
					this.SendPropertyChanging();
					this._IdMenu = value;
					this.SendPropertyChanged("IdMenu");
					this.OnIdMenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int NOT NULL")]
		public int Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this.OnCantidadChanging(value);
					this.SendPropertyChanging();
					this._Cantidad = value;
					this.SendPropertyChanged("Cantidad");
					this.OnCantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblMenu_tblDetallePedido", Storage="_tblMenu", ThisKey="IdMenu", OtherKey="Id", IsForeignKey=true)]
		public tblMenu tblMenu
		{
			get
			{
				return this._tblMenu.Entity;
			}
			set
			{
				tblMenu previousValue = this._tblMenu.Entity;
				if (((previousValue != value) 
							|| (this._tblMenu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblMenu.Entity = null;
						previousValue.tblDetallePedido.Remove(this);
					}
					this._tblMenu.Entity = value;
					if ((value != null))
					{
						value.tblDetallePedido.Add(this);
						this._IdMenu = value.Id;
					}
					else
					{
						this._IdMenu = default(int);
					}
					this.SendPropertyChanged("tblMenu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblPedidos_tblDetallePedido", Storage="_tblPedidos", ThisKey="IdPedido", OtherKey="Id", IsForeignKey=true)]
		public tblPedidos tblPedidos
		{
			get
			{
				return this._tblPedidos.Entity;
			}
			set
			{
				tblPedidos previousValue = this._tblPedidos.Entity;
				if (((previousValue != value) 
							|| (this._tblPedidos.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblPedidos.Entity = null;
						previousValue.tblDetallePedido.Remove(this);
					}
					this._tblPedidos.Entity = value;
					if ((value != null))
					{
						value.tblDetallePedido.Add(this);
						this._IdPedido = value.Id;
					}
					else
					{
						this._IdPedido = default(int);
					}
					this.SendPropertyChanged("tblPedidos");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblFacturaDetalle")]
	public partial class tblFacturaDetalle : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _Cantidad;
		
		private decimal _Subtotal;
		
		private int _IdFactura;
		
		private EntityRef<tblFacturas> _tblFacturas;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnCantidadChanging(int value);
    partial void OnCantidadChanged();
    partial void OnSubtotalChanging(decimal value);
    partial void OnSubtotalChanged();
    partial void OnIdFacturaChanging(int value);
    partial void OnIdFacturaChanged();
    #endregion
		
		public tblFacturaDetalle()
		{
			this._tblFacturas = default(EntityRef<tblFacturas>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int NOT NULL")]
		public int Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this.OnCantidadChanging(value);
					this.SendPropertyChanging();
					this._Cantidad = value;
					this.SendPropertyChanged("Cantidad");
					this.OnCantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subtotal", DbType="Decimal(10,2) NOT NULL")]
		public decimal Subtotal
		{
			get
			{
				return this._Subtotal;
			}
			set
			{
				if ((this._Subtotal != value))
				{
					this.OnSubtotalChanging(value);
					this.SendPropertyChanging();
					this._Subtotal = value;
					this.SendPropertyChanged("Subtotal");
					this.OnSubtotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdFactura", DbType="Int NOT NULL")]
		public int IdFactura
		{
			get
			{
				return this._IdFactura;
			}
			set
			{
				if ((this._IdFactura != value))
				{
					if (this._tblFacturas.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdFacturaChanging(value);
					this.SendPropertyChanging();
					this._IdFactura = value;
					this.SendPropertyChanged("IdFactura");
					this.OnIdFacturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblFacturas_tblFacturaDetalle", Storage="_tblFacturas", ThisKey="IdFactura", OtherKey="Id", IsForeignKey=true)]
		public tblFacturas tblFacturas
		{
			get
			{
				return this._tblFacturas.Entity;
			}
			set
			{
				tblFacturas previousValue = this._tblFacturas.Entity;
				if (((previousValue != value) 
							|| (this._tblFacturas.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblFacturas.Entity = null;
						previousValue.tblFacturaDetalle.Remove(this);
					}
					this._tblFacturas.Entity = value;
					if ((value != null))
					{
						value.tblFacturaDetalle.Add(this);
						this._IdFactura = value.Id;
					}
					else
					{
						this._IdFactura = default(int);
					}
					this.SendPropertyChanged("tblFacturas");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblMenu")]
	public partial class tblMenu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Descripcion;
		
		private decimal _Valor;
		
		private int _Estado;
		
		private EntitySet<tblDetallePedido> _tblDetallePedido;
		
		private EntitySet<tblFacturas> _tblFacturas;
		
		private EntitySet<tbl_FechaClientes> _tbl_FechaClientes;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnValorChanging(decimal value);
    partial void OnValorChanged();
    partial void OnEstadoChanging(int value);
    partial void OnEstadoChanged();
    #endregion
		
		public tblMenu()
		{
			this._tblDetallePedido = new EntitySet<tblDetallePedido>(new Action<tblDetallePedido>(this.attach_tblDetallePedido), new Action<tblDetallePedido>(this.detach_tblDetallePedido));
			this._tblFacturas = new EntitySet<tblFacturas>(new Action<tblFacturas>(this.attach_tblFacturas), new Action<tblFacturas>(this.detach_tblFacturas));
			this._tbl_FechaClientes = new EntitySet<tbl_FechaClientes>(new Action<tbl_FechaClientes>(this.attach_tbl_FechaClientes), new Action<tbl_FechaClientes>(this.detach_tbl_FechaClientes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Valor", DbType="Decimal(10,2) NOT NULL")]
		public decimal Valor
		{
			get
			{
				return this._Valor;
			}
			set
			{
				if ((this._Valor != value))
				{
					this.OnValorChanging(value);
					this.SendPropertyChanging();
					this._Valor = value;
					this.SendPropertyChanged("Valor");
					this.OnValorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Int NOT NULL")]
		public int Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblMenu_tblDetallePedido", Storage="_tblDetallePedido", ThisKey="Id", OtherKey="IdMenu")]
		public EntitySet<tblDetallePedido> tblDetallePedido
		{
			get
			{
				return this._tblDetallePedido;
			}
			set
			{
				this._tblDetallePedido.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblMenu_tblFacturas", Storage="_tblFacturas", ThisKey="Id", OtherKey="IdMenu")]
		public EntitySet<tblFacturas> tblFacturas
		{
			get
			{
				return this._tblFacturas;
			}
			set
			{
				this._tblFacturas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblMenu_tbl_FechaClientes", Storage="_tbl_FechaClientes", ThisKey="Id", OtherKey="IdMenu")]
		public EntitySet<tbl_FechaClientes> tbl_FechaClientes
		{
			get
			{
				return this._tbl_FechaClientes;
			}
			set
			{
				this._tbl_FechaClientes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblDetallePedido(tblDetallePedido entity)
		{
			this.SendPropertyChanging();
			entity.tblMenu = this;
		}
		
		private void detach_tblDetallePedido(tblDetallePedido entity)
		{
			this.SendPropertyChanging();
			entity.tblMenu = null;
		}
		
		private void attach_tblFacturas(tblFacturas entity)
		{
			this.SendPropertyChanging();
			entity.tblMenu = this;
		}
		
		private void detach_tblFacturas(tblFacturas entity)
		{
			this.SendPropertyChanging();
			entity.tblMenu = null;
		}
		
		private void attach_tbl_FechaClientes(tbl_FechaClientes entity)
		{
			this.SendPropertyChanging();
			entity.tblMenu = this;
		}
		
		private void detach_tbl_FechaClientes(tbl_FechaClientes entity)
		{
			this.SendPropertyChanging();
			entity.tblMenu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblMesas")]
	public partial class tblMesas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Descripcion;
		
		private System.Data.Linq.Binary _Imagen;
		
		private EntitySet<tblFacturas> _tblFacturas;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnImagenChanging(System.Data.Linq.Binary value);
    partial void OnImagenChanged();
    #endregion
		
		public tblMesas()
		{
			this._tblFacturas = new EntitySet<tblFacturas>(new Action<tblFacturas>(this.attach_tblFacturas), new Action<tblFacturas>(this.detach_tblFacturas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Imagen", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Imagen
		{
			get
			{
				return this._Imagen;
			}
			set
			{
				if ((this._Imagen != value))
				{
					this.OnImagenChanging(value);
					this.SendPropertyChanging();
					this._Imagen = value;
					this.SendPropertyChanged("Imagen");
					this.OnImagenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblMesas_tblFacturas", Storage="_tblFacturas", ThisKey="Id", OtherKey="IdMesa")]
		public EntitySet<tblFacturas> tblFacturas
		{
			get
			{
				return this._tblFacturas;
			}
			set
			{
				this._tblFacturas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblFacturas(tblFacturas entity)
		{
			this.SendPropertyChanging();
			entity.tblMesas = this;
		}
		
		private void detach_tblFacturas(tblFacturas entity)
		{
			this.SendPropertyChanging();
			entity.tblMesas = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblPedidos")]
	public partial class tblPedidos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _IdMesaOcupacion;
		
		private System.DateTime _Fecha;
		
		private int _IdMesero;
		
		private string _Nombre;
		
		private EntitySet<tblDetallePedido> _tblDetallePedido;
		
		private EntityRef<tblMeseros> _tblMeseros;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdMesaOcupacionChanging(int value);
    partial void OnIdMesaOcupacionChanged();
    partial void OnFechaChanging(System.DateTime value);
    partial void OnFechaChanged();
    partial void OnIdMeseroChanging(int value);
    partial void OnIdMeseroChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    #endregion
		
		public tblPedidos()
		{
			this._tblDetallePedido = new EntitySet<tblDetallePedido>(new Action<tblDetallePedido>(this.attach_tblDetallePedido), new Action<tblDetallePedido>(this.detach_tblDetallePedido));
			this._tblMeseros = default(EntityRef<tblMeseros>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMesaOcupacion", DbType="Int NOT NULL")]
		public int IdMesaOcupacion
		{
			get
			{
				return this._IdMesaOcupacion;
			}
			set
			{
				if ((this._IdMesaOcupacion != value))
				{
					this.OnIdMesaOcupacionChanging(value);
					this.SendPropertyChanging();
					this._IdMesaOcupacion = value;
					this.SendPropertyChanged("IdMesaOcupacion");
					this.OnIdMesaOcupacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMesero", DbType="Int NOT NULL")]
		public int IdMesero
		{
			get
			{
				return this._IdMesero;
			}
			set
			{
				if ((this._IdMesero != value))
				{
					if (this._tblMeseros.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdMeseroChanging(value);
					this.SendPropertyChanging();
					this._IdMesero = value;
					this.SendPropertyChanged("IdMesero");
					this.OnIdMeseroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblPedidos_tblDetallePedido", Storage="_tblDetallePedido", ThisKey="Id", OtherKey="IdPedido")]
		public EntitySet<tblDetallePedido> tblDetallePedido
		{
			get
			{
				return this._tblDetallePedido;
			}
			set
			{
				this._tblDetallePedido.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblMeseros_tblPedidos", Storage="_tblMeseros", ThisKey="IdMesero", OtherKey="Id", IsForeignKey=true)]
		public tblMeseros tblMeseros
		{
			get
			{
				return this._tblMeseros.Entity;
			}
			set
			{
				tblMeseros previousValue = this._tblMeseros.Entity;
				if (((previousValue != value) 
							|| (this._tblMeseros.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblMeseros.Entity = null;
						previousValue.tblPedidos.Remove(this);
					}
					this._tblMeseros.Entity = value;
					if ((value != null))
					{
						value.tblPedidos.Add(this);
						this._IdMesero = value.Id;
					}
					else
					{
						this._IdMesero = default(int);
					}
					this.SendPropertyChanged("tblMeseros");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblDetallePedido(tblDetallePedido entity)
		{
			this.SendPropertyChanging();
			entity.tblPedidos = this;
		}
		
		private void detach_tblDetallePedido(tblDetallePedido entity)
		{
			this.SendPropertyChanging();
			entity.tblPedidos = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblMeseros")]
	public partial class tblMeseros : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Nombre;
		
		private EntitySet<tblPedidos> _tblPedidos;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    #endregion
		
		public tblMeseros()
		{
			this._tblPedidos = new EntitySet<tblPedidos>(new Action<tblPedidos>(this.attach_tblPedidos), new Action<tblPedidos>(this.detach_tblPedidos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblMeseros_tblPedidos", Storage="_tblPedidos", ThisKey="Id", OtherKey="IdMesero")]
		public EntitySet<tblPedidos> tblPedidos
		{
			get
			{
				return this._tblPedidos;
			}
			set
			{
				this._tblPedidos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblPedidos(tblPedidos entity)
		{
			this.SendPropertyChanging();
			entity.tblMeseros = this;
		}
		
		private void detach_tblPedidos(tblPedidos entity)
		{
			this.SendPropertyChanging();
			entity.tblMeseros = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblUsuarios")]
	public partial class tblUsuarios : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Nombre;
		
		private string _Usuario;
		
		private string _Clave;
		
		private int _Estado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnUsuarioChanging(string value);
    partial void OnUsuarioChanged();
    partial void OnClaveChanging(string value);
    partial void OnClaveChanged();
    partial void OnEstadoChanging(int value);
    partial void OnEstadoChanged();
    #endregion
		
		public tblUsuarios()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this.OnUsuarioChanging(value);
					this.SendPropertyChanging();
					this._Usuario = value;
					this.SendPropertyChanged("Usuario");
					this.OnUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Clave", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Clave
		{
			get
			{
				return this._Clave;
			}
			set
			{
				if ((this._Clave != value))
				{
					this.OnClaveChanging(value);
					this.SendPropertyChanging();
					this._Clave = value;
					this.SendPropertyChanged("Clave");
					this.OnClaveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Int NOT NULL")]
		public int Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblFacturas")]
	public partial class tblFacturas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _IdMesa;
		
		private int _IdMenu;
		
		private int _IdEstado;
		
		private string _Nombre;
		
		private string _FechaHoraInicio;
		
		private string _FechaHoraFin;
		
		private EntitySet<tblFacturaDetalle> _tblFacturaDetalle;
		
		private EntityRef<tbl_Estado> _tbl_Estado;
		
		private EntityRef<tblMenu> _tblMenu;
		
		private EntityRef<tblMesas> _tblMesas;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdMesaChanging(int value);
    partial void OnIdMesaChanged();
    partial void OnIdMenuChanging(int value);
    partial void OnIdMenuChanged();
    partial void OnIdEstadoChanging(int value);
    partial void OnIdEstadoChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnFechaHoraInicioChanging(string value);
    partial void OnFechaHoraInicioChanged();
    partial void OnFechaHoraFinChanging(string value);
    partial void OnFechaHoraFinChanged();
    #endregion
		
		public tblFacturas()
		{
			this._tblFacturaDetalle = new EntitySet<tblFacturaDetalle>(new Action<tblFacturaDetalle>(this.attach_tblFacturaDetalle), new Action<tblFacturaDetalle>(this.detach_tblFacturaDetalle));
			this._tbl_Estado = default(EntityRef<tbl_Estado>);
			this._tblMenu = default(EntityRef<tblMenu>);
			this._tblMesas = default(EntityRef<tblMesas>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMesa", DbType="Int NOT NULL")]
		public int IdMesa
		{
			get
			{
				return this._IdMesa;
			}
			set
			{
				if ((this._IdMesa != value))
				{
					if (this._tblMesas.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdMesaChanging(value);
					this.SendPropertyChanging();
					this._IdMesa = value;
					this.SendPropertyChanged("IdMesa");
					this.OnIdMesaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMenu", DbType="Int NOT NULL")]
		public int IdMenu
		{
			get
			{
				return this._IdMenu;
			}
			set
			{
				if ((this._IdMenu != value))
				{
					if (this._tblMenu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdMenuChanging(value);
					this.SendPropertyChanging();
					this._IdMenu = value;
					this.SendPropertyChanged("IdMenu");
					this.OnIdMenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEstado", DbType="Int NOT NULL")]
		public int IdEstado
		{
			get
			{
				return this._IdEstado;
			}
			set
			{
				if ((this._IdEstado != value))
				{
					if (this._tbl_Estado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdEstadoChanging(value);
					this.SendPropertyChanging();
					this._IdEstado = value;
					this.SendPropertyChanged("IdEstado");
					this.OnIdEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaHoraInicio", DbType="NVarChar(50)")]
		public string FechaHoraInicio
		{
			get
			{
				return this._FechaHoraInicio;
			}
			set
			{
				if ((this._FechaHoraInicio != value))
				{
					this.OnFechaHoraInicioChanging(value);
					this.SendPropertyChanging();
					this._FechaHoraInicio = value;
					this.SendPropertyChanged("FechaHoraInicio");
					this.OnFechaHoraInicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaHoraFin", DbType="NVarChar(50)")]
		public string FechaHoraFin
		{
			get
			{
				return this._FechaHoraFin;
			}
			set
			{
				if ((this._FechaHoraFin != value))
				{
					this.OnFechaHoraFinChanging(value);
					this.SendPropertyChanging();
					this._FechaHoraFin = value;
					this.SendPropertyChanged("FechaHoraFin");
					this.OnFechaHoraFinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblFacturas_tblFacturaDetalle", Storage="_tblFacturaDetalle", ThisKey="Id", OtherKey="IdFactura")]
		public EntitySet<tblFacturaDetalle> tblFacturaDetalle
		{
			get
			{
				return this._tblFacturaDetalle;
			}
			set
			{
				this._tblFacturaDetalle.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Estado_tblFacturas", Storage="_tbl_Estado", ThisKey="IdEstado", OtherKey="Id", IsForeignKey=true)]
		public tbl_Estado tbl_Estado
		{
			get
			{
				return this._tbl_Estado.Entity;
			}
			set
			{
				tbl_Estado previousValue = this._tbl_Estado.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Estado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Estado.Entity = null;
						previousValue.tblFacturas.Remove(this);
					}
					this._tbl_Estado.Entity = value;
					if ((value != null))
					{
						value.tblFacturas.Add(this);
						this._IdEstado = value.Id;
					}
					else
					{
						this._IdEstado = default(int);
					}
					this.SendPropertyChanged("tbl_Estado");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblMenu_tblFacturas", Storage="_tblMenu", ThisKey="IdMenu", OtherKey="Id", IsForeignKey=true)]
		public tblMenu tblMenu
		{
			get
			{
				return this._tblMenu.Entity;
			}
			set
			{
				tblMenu previousValue = this._tblMenu.Entity;
				if (((previousValue != value) 
							|| (this._tblMenu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblMenu.Entity = null;
						previousValue.tblFacturas.Remove(this);
					}
					this._tblMenu.Entity = value;
					if ((value != null))
					{
						value.tblFacturas.Add(this);
						this._IdMenu = value.Id;
					}
					else
					{
						this._IdMenu = default(int);
					}
					this.SendPropertyChanged("tblMenu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblMesas_tblFacturas", Storage="_tblMesas", ThisKey="IdMesa", OtherKey="Id", IsForeignKey=true)]
		public tblMesas tblMesas
		{
			get
			{
				return this._tblMesas.Entity;
			}
			set
			{
				tblMesas previousValue = this._tblMesas.Entity;
				if (((previousValue != value) 
							|| (this._tblMesas.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblMesas.Entity = null;
						previousValue.tblFacturas.Remove(this);
					}
					this._tblMesas.Entity = value;
					if ((value != null))
					{
						value.tblFacturas.Add(this);
						this._IdMesa = value.Id;
					}
					else
					{
						this._IdMesa = default(int);
					}
					this.SendPropertyChanged("tblMesas");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblFacturaDetalle(tblFacturaDetalle entity)
		{
			this.SendPropertyChanging();
			entity.tblFacturas = this;
		}
		
		private void detach_tblFacturaDetalle(tblFacturaDetalle entity)
		{
			this.SendPropertyChanging();
			entity.tblFacturas = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vista_Menu2")]
	public partial class Vista_Menu2
	{
		
		private string _Descripcion;
		
		private decimal _Valor;
		
		public Vista_Menu2()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Valor", DbType="Decimal(10,2) NOT NULL")]
		public decimal Valor
		{
			get
			{
				return this._Valor;
			}
			set
			{
				if ((this._Valor != value))
				{
					this._Valor = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vista_Historial")]
	public partial class Vista_Historial
	{
		
		private string _Descripcion;
		
		private string _Estado;
		
		public Vista_Historial()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Color_states")]
	public partial class Color_states
	{
		
		private int _Id;
		
		private string _Descripcion;
		
		private int _IdEstado;
		
		public Color_states()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEstado", DbType="Int NOT NULL")]
		public int IdEstado
		{
			get
			{
				return this._IdEstado;
			}
			set
			{
				if ((this._IdEstado != value))
				{
					this._IdEstado = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_FechaClientes")]
	public partial class tbl_FechaClientes : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _IdCliente;
		
		private int _IdMenu;
		
		private int _IdEstado;
		
		private string _Fecha;
		
		private EntityRef<tbl_Estado> _tbl_Estado;
		
		private EntityRef<tblMenu> _tblMenu;
		
		private EntityRef<tblCliente> _tblCliente;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdClienteChanging(int value);
    partial void OnIdClienteChanged();
    partial void OnIdMenuChanging(int value);
    partial void OnIdMenuChanged();
    partial void OnIdEstadoChanging(int value);
    partial void OnIdEstadoChanged();
    partial void OnFechaChanging(string value);
    partial void OnFechaChanged();
    #endregion
		
		public tbl_FechaClientes()
		{
			this._tbl_Estado = default(EntityRef<tbl_Estado>);
			this._tblMenu = default(EntityRef<tblMenu>);
			this._tblCliente = default(EntityRef<tblCliente>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCliente", DbType="Int NOT NULL")]
		public int IdCliente
		{
			get
			{
				return this._IdCliente;
			}
			set
			{
				if ((this._IdCliente != value))
				{
					if (this._tblCliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdClienteChanging(value);
					this.SendPropertyChanging();
					this._IdCliente = value;
					this.SendPropertyChanged("IdCliente");
					this.OnIdClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMenu", DbType="Int NOT NULL")]
		public int IdMenu
		{
			get
			{
				return this._IdMenu;
			}
			set
			{
				if ((this._IdMenu != value))
				{
					if (this._tblMenu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdMenuChanging(value);
					this.SendPropertyChanging();
					this._IdMenu = value;
					this.SendPropertyChanged("IdMenu");
					this.OnIdMenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEstado", DbType="Int NOT NULL")]
		public int IdEstado
		{
			get
			{
				return this._IdEstado;
			}
			set
			{
				if ((this._IdEstado != value))
				{
					if (this._tbl_Estado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdEstadoChanging(value);
					this.SendPropertyChanging();
					this._IdEstado = value;
					this.SendPropertyChanged("IdEstado");
					this.OnIdEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Estado_tbl_FechaClientes", Storage="_tbl_Estado", ThisKey="IdEstado", OtherKey="Id", IsForeignKey=true)]
		public tbl_Estado tbl_Estado
		{
			get
			{
				return this._tbl_Estado.Entity;
			}
			set
			{
				tbl_Estado previousValue = this._tbl_Estado.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Estado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Estado.Entity = null;
						previousValue.tbl_FechaClientes.Remove(this);
					}
					this._tbl_Estado.Entity = value;
					if ((value != null))
					{
						value.tbl_FechaClientes.Add(this);
						this._IdEstado = value.Id;
					}
					else
					{
						this._IdEstado = default(int);
					}
					this.SendPropertyChanged("tbl_Estado");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblMenu_tbl_FechaClientes", Storage="_tblMenu", ThisKey="IdMenu", OtherKey="Id", IsForeignKey=true)]
		public tblMenu tblMenu
		{
			get
			{
				return this._tblMenu.Entity;
			}
			set
			{
				tblMenu previousValue = this._tblMenu.Entity;
				if (((previousValue != value) 
							|| (this._tblMenu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblMenu.Entity = null;
						previousValue.tbl_FechaClientes.Remove(this);
					}
					this._tblMenu.Entity = value;
					if ((value != null))
					{
						value.tbl_FechaClientes.Add(this);
						this._IdMenu = value.Id;
					}
					else
					{
						this._IdMenu = default(int);
					}
					this.SendPropertyChanged("tblMenu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblCliente_tbl_FechaClientes", Storage="_tblCliente", ThisKey="IdCliente", OtherKey="Id", IsForeignKey=true)]
		public tblCliente tblCliente
		{
			get
			{
				return this._tblCliente.Entity;
			}
			set
			{
				tblCliente previousValue = this._tblCliente.Entity;
				if (((previousValue != value) 
							|| (this._tblCliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblCliente.Entity = null;
						previousValue.tbl_FechaClientes.Remove(this);
					}
					this._tblCliente.Entity = value;
					if ((value != null))
					{
						value.tbl_FechaClientes.Add(this);
						this._IdCliente = value.Id;
					}
					else
					{
						this._IdCliente = default(int);
					}
					this.SendPropertyChanged("tblCliente");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblCliente")]
	public partial class tblCliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _IdCliente;
		
		private EntitySet<tbl_FechaClientes> _tbl_FechaClientes;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdClienteChanging(int value);
    partial void OnIdClienteChanged();
    #endregion
		
		public tblCliente()
		{
			this._tbl_FechaClientes = new EntitySet<tbl_FechaClientes>(new Action<tbl_FechaClientes>(this.attach_tbl_FechaClientes), new Action<tbl_FechaClientes>(this.detach_tbl_FechaClientes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCliente", DbType="Int NOT NULL")]
		public int IdCliente
		{
			get
			{
				return this._IdCliente;
			}
			set
			{
				if ((this._IdCliente != value))
				{
					this.OnIdClienteChanging(value);
					this.SendPropertyChanging();
					this._IdCliente = value;
					this.SendPropertyChanged("IdCliente");
					this.OnIdClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblCliente_tbl_FechaClientes", Storage="_tbl_FechaClientes", ThisKey="Id", OtherKey="IdCliente")]
		public EntitySet<tbl_FechaClientes> tbl_FechaClientes
		{
			get
			{
				return this._tbl_FechaClientes;
			}
			set
			{
				this._tbl_FechaClientes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_FechaClientes(tbl_FechaClientes entity)
		{
			this.SendPropertyChanging();
			entity.tblCliente = this;
		}
		
		private void detach_tbl_FechaClientes(tbl_FechaClientes entity)
		{
			this.SendPropertyChanging();
			entity.tblCliente = null;
		}
	}
	
	public partial class SearchResult
	{
		
		private string _Descripcion;
		
		private decimal _Valor;
		
		public SearchResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Valor", DbType="Decimal(10,2) NOT NULL")]
		public decimal Valor
		{
			get
			{
				return this._Valor;
			}
			set
			{
				if ((this._Valor != value))
				{
					this._Valor = value;
				}
			}
		}
	}
	
	public partial class show_menuResult
	{
		
		private string _Orden;
		
		private int _Id;
		
		public show_menuResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Orden", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Orden
		{
			get
			{
				return this._Orden;
			}
			set
			{
				if ((this._Orden != value))
				{
					this._Orden = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
